theme: jekyll-theme-Cayman
title: REAL TIME FLORIDA COASTAL GUIDANCE
author: Peyman Taeb
email: FL-ASGS@fit.edu
description: East Central Coast, Indian River Lagoon, and Brevard County
favicon:     "ECFL-IRL/logo/FIT_logo.jpg"
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

